openapi: 2.0.0
info:
  title: "Mozilla Doorman"
  description: |
    *Doorman* is an **authorization micro-service** that allows to checks if an arbitrary subject is allowed to perform an action on a resource, based on a set of rules (policies).

    It takes a set of YAML files like the one below and answers authorization requests by matching the rules:

    ```YAML
    service: https://api.service.org
    jwtIssuer: https://auth.mozilla.auth0.com/
    policies:
      -
        id: crud-articles
        description: Editors can CRUD articles
        principals:
          - role:editor
        actions:
          - create
          - read
          - delete
          - update
        resources:
          - article
        effect: allow
    ```

    ### Workflow with OpenID

    When a service takes advantage of *Doorman*, a typical workflow is:

    1. Users obtain an access token from an Identity Provider (eg. Auth0)
    1. They use it to call a service API endpoint
    1. The service posts an authorization request on *Doorman* to check if the user is allowed to perform a specific action
    1. *Doorman* uses the `Origin` request header to select the set of policies to match
    1. *Doorman* fetches the user infos using the provided access token and builds a list of strings (principals) to characterize this user
    1. *Doorman* matches the policies and returns true or allowed, along with the list of principals
    1. Based on the *Doorman* response, the service denies the original request or executes it

    *Doorman* will verify that the specified Access token (or ID token) is valid.

    The authorization request **principals** will be built from the user profile information like this:

    * `"sub"`: `userid:{}`
    * `"email"`: `email:{}` (*optional*)
    * `"groups"`: `group:{}, group:{}, ...` (*optional*)


    ### Without authentication/OpenID

    If the identity provider is not configured for a service, no authentication is required and the principals
    are posted in the authorization body.

    It is not especially recommended, but it can give a certain amount of flexibility when authentication is fully managed on the service.

    A typical workflow in this case would be:

    1. Users call the service API endpoint
    1. The service authenticates the user and builds the list of principals
    1. The service posts an authorization request on *Doorman* containing the list of principals to check if the user is allowed


    ### API Summary

    Basically, use **POST /allowed** to check authorization requests.

    **Request**:

    ```HTTP

    POST /allowed HTTP/1.1
    Origin: https://api.service.org
    Authorization: Bearer f2457yu86yikhmbh

    {
      "action" : "delete",
      "resource": "articles/doorman-introduce",
      "context": {
        "env": "stage",
        "roles": ["editor"]
      }
    }
    ```

    **Response**:

    ```HTTP

    HTTP/1.1 200 OK
    Content-Type: application/json

    {
      "allowed": true,
      "principals": [
        "role:editor",
        "userid:myself"
      ]
    }
    ```

  version: "0.1"
  contact:
    url: "irc://irc.mozilla.org:6696/#product-delivery"
  license:
    name: "Mozilla Public License 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

tags:
- name: Doorman
  description: Main API endpoints.
- name: Utilities
  description: Operational and metadata endpoints.

paths:

  /allowed:
    post:
      summary: Check authorization request
      description: |
        Are those `principals` allowed to perform this `action` on this `resource` in this `context`?

        With authentication enabled, the principals are either read from the Identity Provider user info endpoint or directly from the JSON Web Token payload
        if an ID token is provided.

      operationId: "allowed"
      consumes:
        - application/json
      produces:
      - "application/json"
      parameters:
        - in: header
          name: Origin
          type: string
          description: |
            The service identifier (eg. `https://api.service.org`). It must match one of the known service from the policies files.

        - in: header
          name: Authorization
          type: string
          description: |
            With OpenID enabled, a valid Access token (or JSON Web ID Token) must be provided in the `Authorization` request header.
            (eg. `Bearer eyJ0eXAiOiJKV1QiLCJhbG...9USXpOalEzUXpV`)

        - in: body
          description: |
            Authorization request as JSON.

            Note that **every field is optional**.

          required: true
          schema:
            type: object
            properties:
              principals:
                description: |
                  **Only without authentication**

                  Arbitrary list of strings (eg. `userid:alice`, `group:editors`).

                type: array
                items:
                  type: string
              action:
                description: Any domain specific action (eg. `read`, `delete`, `signoff`)
                type: string
              resource:
                description: Any resource (eg. `blocklist`, `/update/rules/35`)
                type: string
              context:
                description: |
                  The context can contain any extra information to be matched in policies conditions.
                  The context field `remoteIP` will be forced by the server.
                  The values provided in the `roles` context field will expand the principals with extra `role:{}` values.

                type: object
                properties:
                  roles:
                    type: array
                    items:
                      type: string
          example:
            principals: ["userid:ldap|ada", "email:ada@lau.co"]
            action: create
            resource: comment
            context:
              env:
                - stage
              roles:
                - changer
      responses:
        "400":
          description: "Missing headers or invalid posted data."
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: Missing `Origin` request header
        "401":
          description: "OpenID token is invalid."
        "200":
          description: "Return whether it is allowed or not."
          schema:
            type: object
            properties:
              allowed:
                type: boolean
              principals:
                type: array
                items:
                  type: string
          example:
            allowed: true
            principals: ["userid:ldap|ada", "email:ada@lau.co", "tag:mayor", "role:changer"]
      tags:
      - Doorman

  /__reload__:
    post:
      summary: "Reload the policies"
      description: |
        Reload the policies (synchronously). This endpoint is meant to be used as a Web hook when policies files were changed.

        > It would be wise to limit the access to this endpoint (e.g. by IP on reverse proxy)

      operationId: "reload"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Reloaded successfully."
          schema:
            type: object
            properties:
              success:
                type: boolean
          example:
            success: true

        "500":
          description: "Reload failed."
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            success: false
            message: could not parse YAML in "https://github.com/ops/conf/policies.yaml"
      tags:
      - Doorman

  /__heartbeat__:
    get:
      summary: "Is the server working properly? What is failing?"
      operationId: "heartbeat"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Server working properly"
          schema:
            type: "object"
          example:
        "503":
          description: "One or more subsystems failing."
          schema:
            type: "object"
          example:
      tags:
      - Utilities

  /__lbheartbeat__:
    get:
      summary: "Is the server reachable?"
      operationId: "lbheartbeat"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Server reachable"
          schema:
            type: "object"
            properties:
              ok:
                type: boolean
          example:
            ok: true
      tags:
      - Utilities

  /__version__:
    get:
      summary: "Running instance version information"
      operationId: "version"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Return the running instance version information"
          schema:
            type: "object"
            properties:
              source:
                type: string
              version:
                type: string
              commit:
                type: string
              build:
                type: string
          example:
            source: https://github.com/mozilla/doorman
            version: "1.0"
            commit: 490ed70efff482d17a
            build: "20171102"
      tags:
      - Utilities

  /__api__:
    get:
      summary: "Open API Specification documentation."
      operationId: "doc"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Return the Open Api Specification."
          schema:
            type: "object"
      tags:
      - Utilities

  /contribute.json:
    get:
      summary: "Open source contributing information"
      operationId: "contribute"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Return open source contributing information."
          schema:
            type: "object"
      tags:
      - Utilities
